[workspace]
members = [
    "libra",
    "compat",
    # MLS:
    "mls/move-language-server",
    "mls/analysis",
    "mls/move-executor",
    "mls/dialects",
    "mls/utils",
    "mls/integration_tests"
]
