edition = "2018"
max_width = 98

# let a = Foo { x, y, z };
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#use_field_init_shorthand
use_field_init_shorthand = true

# We want oun imports order
reorder_imports = false # Reorder import statements alphabetically
