[package]
name = "move-executor"
version = "0.1.0"
authors = ["Maksim Kurnikov <maxim.kurnikov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.28"
serde = "1.0.106"
serde_json = "1.0.52"
clap = "2.33.1"
textwrap = "0.12.1"
num-format = { version = "0.4", features = ["std"] }
enum-iterator = "0.6.0"

libra-types = { git = "https://github.com/dfinance/libra.git", branch = "release-1.0" }
move-vm-runtime = { git = "https://github.com/dfinance/libra.git", branch = "release-1.0", features = ["debug_module"] }
move-vm-types = { git = "https://github.com/dfinance/libra.git", branch = "release-1.0" }
lcs = { package = "libra-canonical-serialization", git = "https://github.com/dfinance/libra.git", branch = "release-1.0" }
vm = { git = "https://github.com/dfinance/libra.git", branch = "release-1.0" }
move-core-types = { git = "https://github.com/dfinance/libra.git", branch = "release-1.0" }
move-lang = { git = "https://github.com/dfinance/libra.git", branch = "release-1.0" }
move-ir-types = { git = "https://github.com/dfinance/libra.git", branch = "release-1.0" }
vm-genesis = { git = "https://github.com/dfinance/libra.git", branch = "release-1.0" }
compiled-stdlib = { git = "https://github.com/dfinance/libra.git", branch = "release-1.0" }
errmapgen = { git = "https://github.com/dfinance/libra.git", branch = "release-1.0" }
libra-move-core-types = { package = "move-core-types", git = "https://github.com/dfinance/libra.git", branch = "master" }

resources = { path = "../resources" }
lang = { path = "../lang" }
git-hash = { path = "../common/git-hash" }
