name: "Pull Request Labeler"
on:
  pull_request:
    types:
      - opened
      - unlabeled
      - ready_for_review
      - synchronize

jobs:
  triage:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/labeler@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labels.yml
          sync-labels: true
